#!/usr/bin/env bash
set -euo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_ROOT="$(cd "$SELF_DIR/.." && pwd)"
FRONTEND_DIR="$SERVICE_ROOT/frontend/admin"
OUTPUT_DIR="$SERVICE_ROOT/internal/api/admin/ui_dist"

if ! command -v npm >/dev/null 2>&1; then
  echo "npm is required to build the admin UI" >&2
  exit 1
fi

cd "$FRONTEND_DIR"

if [ -f package-lock.json ]; then
  npm ci
else
  npm install
fi

npm run test:contracts
npm run build

rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"
cp -R "$FRONTEND_DIR/dist/." "$OUTPUT_DIR/"

# --- Install Wizard UI ---
INSTALL_OUTPUT_DIR="$SERVICE_ROOT/internal/api/install/install_ui_dist"
rm -rf "$INSTALL_OUTPUT_DIR"
mkdir -p "$INSTALL_OUTPUT_DIR"

if [ ! -f "$FRONTEND_DIR/dist/install.html" ]; then
  echo "FATAL: dist/install.html not generated by Vite multi-entry build"
  exit 1
fi

cp "$FRONTEND_DIR/dist/install.html" "$INSTALL_OUTPUT_DIR/"
echo "==> Install wizard UI copied to $INSTALL_OUTPUT_DIR"

if [ ! -f "$FRONTEND_DIR/dist/setup.html" ]; then
  echo "FATAL: dist/setup.html not generated by Vite multi-entry build"
  exit 1
fi
echo "==> Setup UI available at $OUTPUT_DIR/setup.html"
