version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign

  exclusions:
    paths:
      - vendor

formatters:
  enable:
    - gofmt
  exclusions:
    paths:
      - vendor

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
